import datetime
import json

import requests

import constants


class Offsets:
    def __init__(self, update=False) -> None:
        super().__init__()
        self.dwCSGOInput: int | None = None
        self.dwEntityList: int | None = None
        self.dwGameEntitySystem: int | None = None
        self.dwGameEntitySystem_highestEntityIndex: int | None = None
        self.dwGameRules: int | None = None
        self.dwGlobalVars: int | None = None
        self.dwGlowManager: int | None = None
        self.dwLocalPlayerController: int | None = None
        self.dwLocalPlayerPawn: int | None = None
        self.dwPlantedC4: int | None = None
        self.dwPrediction: int | None = None
        self.dwSensitivity: int | None = None
        self.dwSensitivity_sensitivity: int | None = None
        self.dwViewAngles: int | None = None
        self.dwViewMatrix: int | None = None
        self.dwViewRender: int | None = None
        self.dwWeaponC4: int | None = None
        self.dwBuildNumber: int | None = None
        self.dwNetworkGameClient: int | None = None
        self.dwNetworkGameClient_clientTickCount: int | None = None
        self.dwNetworkGameClient_deltaTick: int | None = None
        self.dwNetworkGameClient_isBackgroundMap: int | None = None
        self.dwNetworkGameClient_localPlayer: int | None = None
        self.dwNetworkGameClient_maxClients: int | None = None
        self.dwNetworkGameClient_serverTickCount: int | None = None
        self.dwNetworkGameClient_signOnState: int | None = None
        self.dwWindowHeight: int | None = None
        self.dwWindowWidth: int | None = None
        self.dwInputSystem: int | None = None
        self.dwGameTypes: int | None = None
        self.dwGameTypes_mapName: int | None = None
        self.dwSoundSystem: int | None = None
        self.dwSoundSystem_engineViewData: int | None = None
        self.m_CommandContext: int | None = None
        self.m_bIsHLTV: int | None = None
        self.m_bIsLocalPlayerController: int | None = None
        self.m_bKnownTeamMismatch: int | None = None
        self.m_hPawn: int | None = None
        self.m_hPredictedPawn: int | None = None
        self.m_hSplitOwner: int | None = None
        self.m_hSplitScreenPlayers: int | None = None
        self.m_iConnected: int | None = None
        self.m_iDesiredFOV: int | None = None
        self.m_iszPlayerName: int | None = None
        self.m_nFinalPredictedTick: int | None = None
        self.m_nInButtonsWhichAreToggles: int | None = None
        self.m_nSplitScreenSlot: int | None = None
        self.m_nTickBase: int | None = None
        self.m_steamID: int | None = None
        self.m_flFOVRate: int | None = None
        self.m_flFOVTime: int | None = None
        self.m_flLastShotFOV: int | None = None
        self.m_hZoomOwner: int | None = None
        self.m_iFOV: int | None = None
        self.m_iFOVStart: int | None = None
        self.m_DefaultLoadoutSlot: int | None = None
        self.m_GearSlot: int | None = None
        self.m_GearSlotPosition: int | None = None
        self.m_WeaponCategory: int | None = None
        self.m_WeaponType: int | None = None
        self.m_angPivotAngle: int | None = None
        self.m_bCannotShootUnderwater: int | None = None
        self.m_bHasBurstMode: int | None = None
        self.m_bHideViewModelWhenZoomed: int | None = None
        self.m_bIsFullAuto: int | None = None
        self.m_bIsRevolver: int | None = None
        self.m_bMeleeWeapon: int | None = None
        self.m_bUnzoomsAfterShot: int | None = None
        self.m_eSilencerType: int | None = None
        self.m_flArmorRatio: int | None = None
        self.m_flAttackMovespeedFactor: int | None = None
        self.m_flBotAudibleRange: int | None = None
        self.m_flCycleTime: int | None = None
        self.m_flFlinchVelocityModifierLarge: int | None = None
        self.m_flFlinchVelocityModifierSmall: int | None = None
        self.m_flHeadshotMultiplier: int | None = None
        self.m_flHeatPerShot: int | None = None
        self.m_flIdleInterval: int | None = None
        self.m_flInaccuracyAltSoundThreshold: int | None = None
        self.m_flInaccuracyCrouch: int | None = None
        self.m_flInaccuracyFire: int | None = None
        self.m_flInaccuracyJump: int | None = None
        self.m_flInaccuracyJumpApex: int | None = None
        self.m_flInaccuracyJumpInitial: int | None = None
        self.m_flInaccuracyLadder: int | None = None
        self.m_flInaccuracyLand: int | None = None
        self.m_flInaccuracyMove: int | None = None
        self.m_flInaccuracyPitchShift: int | None = None
        self.m_flInaccuracyReload: int | None = None
        self.m_flInaccuracyStand: int | None = None
        self.m_flIronSightFOV: int | None = None
        self.m_flIronSightLooseness: int | None = None
        self.m_flIronSightPivotForward: int | None = None
        self.m_flIronSightPullUpSpeed: int | None = None
        self.m_flIronSightPutDownSpeed: int | None = None
        self.m_flMaxSpeed: int | None = None
        self.m_flPenetration: int | None = None
        self.m_flRange: int | None = None
        self.m_flRangeModifier: int | None = None
        self.m_flRecoilAngle: int | None = None
        self.m_flRecoilAngleVariance: int | None = None
        self.m_flRecoilMagnitude: int | None = None
        self.m_flRecoilMagnitudeVariance: int | None = None
        self.m_flRecoveryTimeCrouch: int | None = None
        self.m_flRecoveryTimeCrouchFinal: int | None = None
        self.m_flRecoveryTimeStand: int | None = None
        self.m_flRecoveryTimeStandFinal: int | None = None
        self.m_flSpread: int | None = None
        self.m_flThrowVelocity: int | None = None
        self.m_flTimeToIdleAfterFire: int | None = None
        self.m_flZoomTime0: int | None = None
        self.m_flZoomTime1: int | None = None
        self.m_flZoomTime2: int | None = None
        self.m_nCrosshairDeltaDistance: int | None = None
        self.m_nCrosshairMinDistance: int | None = None
        self.m_nDamage: int | None = None
        self.m_nKillAward: int | None = None
        self.m_nNumBullets: int | None = None
        self.m_nPrice: int | None = None
        self.m_nPrimaryReserveAmmoMax: int | None = None
        self.m_nRecoilSeed: int | None = None
        self.m_nRecoveryTransitionEndBullet: int | None = None
        self.m_nRecoveryTransitionStartBullet: int | None = None
        self.m_nSecondaryReserveAmmoMax: int | None = None
        self.m_nSpreadSeed: int | None = None
        self.m_nTracerFrequency: int | None = None
        self.m_nZoomFOV1: int | None = None
        self.m_nZoomFOV2: int | None = None
        self.m_nZoomLevels: int | None = None
        self.m_sWrongTeamMsg: int | None = None
        self.m_szAimsightLensMaskModel: int | None = None
        self.m_szAnimClass: int | None = None
        self.m_szAnimExtension: int | None = None
        self.m_szEjectBrassEffect: int | None = None
        self.m_szHeatEffect: int | None = None
        self.m_szMagazineModel: int | None = None
        self.m_szMuzzleFlashParticleAlt: int | None = None
        self.m_szMuzzleFlashThirdPersonParticle: int | None = None
        self.m_szMuzzleFlashThirdPersonParticleAlt: int | None = None
        self.m_szName: int | None = None
        self.m_szPlayerModel: int | None = None
        self.m_szTracerParticle: int | None = None
        self.m_szUseRadioSubtitle: int | None = None
        self.m_szViewModel: int | None = None
        self.m_szWorldDroppedModel: int | None = None
        self.m_vecIronSightEyePos: int | None = None
        self.m_PathIndex: int | None = None
        self.m_designerName: int | None = None
        self.m_fDataObjectTypes: int | None = None
        self.m_flags: int | None = None
        self.m_name: int | None = None
        self.m_nameStringableIndex: int | None = None
        self.m_pNext: int | None = None
        self.m_pNextByClass: int | None = None
        self.m_pPrev: int | None = None
        self.m_pPrevByClass: int | None = None
        self.m_worldGroupId: int | None = None
        self.m_CScriptComponent: int | None = None
        self.m_bVisibleinPVS: int | None = None
        self.m_iszPrivateVScripts: int | None = None
        self.m_pEntity: int | None = None
        self.m_angAbsRotation: int | None = None
        self.m_angRotation: int | None = None
        self.m_bBoneMergeFlex: int | None = None
        self.m_bDebugAbsOriginChanges: int | None = None
        self.m_bDirtyBoneMergeBoneToRoot: int | None = None
        self.m_bDirtyBoneMergeInfo: int | None = None
        self.m_bDirtyHierarchy: int | None = None
        self.m_bDormant: int | None = None
        self.m_bForceParentToBeNetworked: int | None = None
        self.m_bNetworkedAnglesChanged: int | None = None
        self.m_bNetworkedPositionChanged: int | None = None
        self.m_bNetworkedScaleChanged: int | None = None
        self.m_bWillBeCallingPostDataUpdate: int | None = None
        self.m_flAbsScale: int | None = None
        self.m_flClientLocalScale: int | None = None
        self.m_flScale: int | None = None
        self.m_flZOffset: int | None = None
        self.m_hParent: int | None = None
        self.m_hierarchyAttachName: int | None = None
        self.m_nDoNotSetAnimTimeInInvalidatePhysicsCount: int | None = None
        self.m_nHierarchicalDepth: int | None = None
        self.m_nHierarchyType: int | None = None
        self.m_nLatchAbsOrigin: int | None = None
        self.m_nParentAttachmentOrBone: int | None = None
        self.m_nodeToWorld: int | None = None
        self.m_pChild: int | None = None
        self.m_pNextSibling: int | None = None
        self.m_pOwner: int | None = None
        self.m_pParent: int | None = None
        self.m_vRenderOrigin: int | None = None
        self.m_vecAbsOrigin: int | None = None
        self.m_vecOrigin: int | None = None
        self.m_bEligibleForScreenHighlight: int | None = None
        self.m_bFlashing: int | None = None
        self.m_bGlowing: int | None = None
        self.m_fGlowColor: int | None = None
        self.m_flGlowStartTime: int | None = None
        self.m_flGlowTime: int | None = None
        self.m_glowColorOverride: int | None = None
        self.m_iGlowTeam: int | None = None
        self.m_iGlowType: int | None = None
        self.m_nGlowRange: int | None = None
        self.m_nGlowRangeMin: int | None = None
        self.m_bDirtyMotionType: int | None = None
        self.m_bDisableSolidCollisionsForHierarchy: int | None = None
        self.m_bIsAnimationEnabled: int | None = None
        self.m_bIsGeneratingLatchedParentSpaceState: int | None = None
        self.m_bUseParentRenderBounds: int | None = None
        self.m_materialGroup: int | None = None
        self.m_modelState: int | None = None
        self.m_nHitboxSet: int | None = None
        self.m_Item: int | None = None
        self.m_iExternalItemProviderRegisteredToken: int | None = None
        self.m_ullRegisteredAsItemID: int | None = None
        self.m_CBodyComponent: int | None = None
        self.m_DataChangeEventRef: int | None = None
        self.m_EntClientFlags: int | None = None
        self.m_ListEntry: int | None = None
        self.m_MoveCollide: int | None = None
        self.m_MoveType: int | None = None
        self.m_NetworkTransmitComponent: int | None = None
        self.m_Particles: int | None = None
        self.m_aThinkFunctions: int | None = None
        self.m_bAnimTimeChanged: int | None = None
        self.m_bAnimatedEveryTick: int | None = None
        self.m_bApplyLayerMatchIDToModel: int | None = None
        self.m_bClientSideRagdoll: int | None = None
        self.m_bDisabledContextThinks: int | None = None
        self.m_bHasAddedVarsToInterpolation: int | None = None
        self.m_bHasSuccessfullyInterpolated: int | None = None
        self.m_bInterpolateEvenWithNoModel: int | None = None
        self.m_bPredictable: int | None = None
        self.m_bPredictionEligible: int | None = None
        self.m_bRenderEvenWhenNotSuccessfullyInterpolated: int | None = None
        self.m_bRenderWithViewModels: int | None = None
        self.m_bSimulationTimeChanged: int | None = None
        self.m_bTakesDamage: int | None = None
        self.m_dependencies: int | None = None
        self.m_fBBoxVisFlags: int | None = None
        self.m_fEffects: int | None = None
        self.m_fFlags: int | None = None
        self.m_flAnimTime: int | None = None
        self.m_flCreateTime: int | None = None
        self.m_flElasticity: int | None = None
        self.m_flFriction: int | None = None
        self.m_flGravityScale: int | None = None
        self.m_flNavIgnoreUntilTime: int | None = None
        self.m_flProxyRandomValue: int | None = None
        self.m_flSimulationTime: int | None = None
        self.m_flSpeed: int | None = None
        self.m_flTimeScale: int | None = None
        self.m_flWaterLevel: int | None = None
        self.m_hEffectEntity: int | None = None
        self.m_hGroundEntity: int | None = None
        self.m_hOldMoveParent: int | None = None
        self.m_hOwnerEntity: int | None = None
        self.m_hSceneObjectController: int | None = None
        self.m_hThink: int | None = None
        self.m_iCurrentThinkContext: int | None = None
        self.m_iEFlags: int | None = None
        self.m_iHealth: int | None = None
        self.m_iMaxHealth: int | None = None
        self.m_iTeamNum: int | None = None
        self.m_lifeState: int | None = None
        self.m_nActualMoveType: int | None = None
        self.m_nBloodType: int | None = None
        self.m_nCreationTick: int | None = None
        self.m_nFirstPredictableCommand: int | None = None
        self.m_nGroundBodyIndex: int | None = None
        self.m_nInterpolationLatchDirtyFlags: int | None = None
        self.m_nLastPredictableCommand: int | None = None
        self.m_nLastThinkTick: int | None = None
        self.m_nNextScriptVarRecordID: int | None = None
        self.m_nNextThinkTick: int | None = None
        self.m_nNoInterpolationTick: int | None = None
        self.m_nPlatformType: int | None = None
        self.m_nSceneObjectOverrideFlags: int | None = None
        self.m_nSimulationTick: int | None = None
        self.m_nSplitUserPlayerPredictionSlot: int | None = None
        self.m_nSubclassID: int | None = None
        self.m_nTakeDamageFlags: int | None = None
        self.m_nVisibilityNoInterpolationTick: int | None = None
        self.m_nWaterType: int | None = None
        self.m_pCollision: int | None = None
        self.m_pGameSceneNode: int | None = None
        self.m_pRenderComponent: int | None = None
        self.m_sUniqueHammerID: int | None = None
        self.m_spawnflags: int | None = None
        self.m_tokLayerMatchID: int | None = None
        self.m_ubInterpolationFrame: int | None = None
        self.m_vecAbsVelocity: int | None = None
        self.m_vecAngVelocity: int | None = None
        self.m_vecBaseVelocity: int | None = None
        self.m_vecPredictedScriptFloatIDs: int | None = None
        self.m_vecPredictedScriptFloats: int | None = None
        self.m_vecVelocity: int | None = None
        self.m_CHitboxComponent: int | None = None
        self.m_CRenderComponent: int | None = None
        self.m_ClientOverrideTint: int | None = None
        self.m_Collision: int | None = None
        self.m_ConfigEntitiesToPropagateMaterialDecalsTo: int | None = None
        self.m_Glow: int | None = None
        self.m_LastHitGroup: int | None = None
        self.m_bAllowFadeInView: int | None = None
        self.m_bInitModelEffects: int | None = None
        self.m_bIsStaticProp: int | None = None
        self.m_bNoInterpolate: int | None = None
        self.m_bRenderToCubemaps: int | None = None
        self.m_bUseClientOverrideTint: int | None = None
        self.m_clrRender: int | None = None
        self.m_fadeMaxDist: int | None = None
        self.m_fadeMinDist: int | None = None
        self.m_flDecalHealBloodRate: int | None = None
        self.m_flDecalHealHeightRate: int | None = None
        self.m_flFadeScale: int | None = None
        self.m_flGlowBackfaceMult: int | None = None
        self.m_flShadowStrength: int | None = None
        self.m_iOldHealth: int | None = None
        self.m_nAddDecal: int | None = None
        self.m_nDecalsAdded: int | None = None
        self.m_nLastAddDecal: int | None = None
        self.m_nObjectCulling: int | None = None
        self.m_nRenderFX: int | None = None
        self.m_nRenderMode: int | None = None
        self.m_pClientAlphaProperty: int | None = None
        self.m_vDecalForwardAxis: int | None = None
        self.m_vDecalPosition: int | None = None
        self.m_vecRenderAttributes: int | None = None
        self.m_vecViewOffset: int | None = None
        self.m_ServerViewAngleChanges: int | None = None
        self.m_bIsSwappingToPredictableController: int | None = None
        self.m_flDeathTime: int | None = None
        self.m_flFOVSensitivityAdjust: int | None = None
        self.m_flLastCameraSetupTime: int | None = None
        self.m_flMouseSensitivity: int | None = None
        self.m_flOldSimulationTime: int | None = None
        self.m_flPredictionErrorTime: int | None = None
        self.m_hController: int | None = None
        self.m_iHideHUD: int | None = None
        self.m_nHighestConsumedServerViewAngleChangeIndex: int | None = None
        self.m_nLastExecutedCommandNumber: int | None = None
        self.m_nLastExecutedCommandTick: int | None = None
        self.m_pAutoaimServices: int | None = None
        self.m_pCameraServices: int | None = None
        self.m_pFlashlightServices: int | None = None
        self.m_pItemServices: int | None = None
        self.m_pMovementServices: int | None = None
        self.m_pObserverServices: int | None = None
        self.m_pUseServices: int | None = None
        self.m_pWaterServices: int | None = None
        self.m_pWeaponServices: int | None = None
        self.m_skybox3d: int | None = None
        self.m_vOldOrigin: int | None = None
        self.m_vecLastCameraSetupLocalOrigin: int | None = None
        self.m_vecPredictionError: int | None = None
        self.v_angle: int | None = None
        self.v_anglePrevious: int | None = None
        self.m_ArmorValue: int | None = None
        self.m_EconGloves: int | None = None
        self.m_GunGameImmunityColor: int | None = None
        self.m_PredictedDamageTags: int | None = None
        self.m_RetakesMVPBoostExtraUtility: int | None = None
        self.m_aimPunchAngle: int | None = None
        self.m_aimPunchAngleVel: int | None = None
        self.m_aimPunchCache: int | None = None
        self.m_aimPunchTickBase: int | None = None
        self.m_aimPunchTickFraction: int | None = None
        self.m_angShootAngleHistory: int | None = None
        self.m_angStashedShootAngles: int | None = None
        self.m_bGrenadeParametersStashed: int | None = None
        self.m_bHasDeathInfo: int | None = None
        self.m_bHasFemaleVoice: int | None = None
        self.m_bInBombZone: int | None = None
        self.m_bInBuyZone: int | None = None
        self.m_bInHostageRescueZone: int | None = None
        self.m_bInLanding: int | None = None
        self.m_bInNoDefuseArea: int | None = None
        self.m_bIsBuyMenuOpen: int | None = None
        self.m_bIsDefusing: int | None = None
        self.m_bIsGrabbingHostage: int | None = None
        self.m_bIsScoped: int | None = None
        self.m_bIsWalking: int | None = None
        self.m_bKilledByHeadshot: int | None = None
        self.m_bLastHeadBoneTransformIsValid: int | None = None
        self.m_bLeftHanded: int | None = None
        self.m_bMustSyncRagdollState: int | None = None
        self.m_bNeedToReApplyGloves: int | None = None
        self.m_bOldIsScoped: int | None = None
        self.m_bOnGroundLastTick: int | None = None
        self.m_bPrevDefuser: int | None = None
        self.m_bPrevHelmet: int | None = None
        self.m_bPreviouslyInBuyZone: int | None = None
        self.m_bRagdollDamageHeadshot: int | None = None
        self.m_bResumeZoom: int | None = None
        self.m_bRetakesHasDefuseKit: int | None = None
        self.m_bRetakesMVPLastRound: int | None = None
        self.m_bSkipOneHeadConstraintUpdate: int | None = None
        self.m_bWaitForNoAttack: int | None = None
        self.m_entitySpottedState: int | None = None
        self.m_fSwitchedHandednessTime: int | None = None
        self.m_flDeathInfoTime: int | None = None
        self.m_flEmitSoundTime: int | None = None
        self.m_flFlinchStack: int | None = None
        self.m_flHealthShotBoostExpirationTime: int | None = None
        self.m_flHitHeading: int | None = None
        self.m_flLandingStartTime: int | None = None
        self.m_flLandingTimeSeconds: int | None = None
        self.m_flLastFiredWeaponTime: int | None = None
        self.m_flNextSprayDecalTime: int | None = None
        self.m_flOldFallVelocity: int | None = None
        self.m_flSlopeDropHeight: int | None = None
        self.m_flSlopeDropOffset: int | None = None
        self.m_flTimeOfLastInjury: int | None = None
        self.m_flVelocityModifier: int | None = None
        self.m_flViewmodelFOV: int | None = None
        self.m_flViewmodelOffsetX: int | None = None
        self.m_flViewmodelOffsetY: int | None = None
        self.m_flViewmodelOffsetZ: int | None = None
        self.m_grenadeParameterStashTime: int | None = None
        self.m_iBlockingUseActionInProgress: int | None = None
        self.m_iRetakesMVPBoostItem: int | None = None
        self.m_iRetakesOffering: int | None = None
        self.m_iRetakesOfferingCard: int | None = None
        self.m_iShotsFired: int | None = None
        self.m_ignoreLadderJumpTime: int | None = None
        self.m_lastLandTime: int | None = None
        self.m_nEconGlovesChanged: int | None = None
        self.m_nHighestAppliedDamageTagTick: int | None = None
        self.m_nHitBodyPart: int | None = None
        self.m_nLastKillerIndex: int | None = None
        self.m_nPrevArmorVal: int | None = None
        self.m_nPrevGrenadeAmmoCount: int | None = None
        self.m_nPrevHighestReceivedDamageTagTick: int | None = None
        self.m_nRagdollDamageBone: int | None = None
        self.m_nWhichBombZone: int | None = None
        self.m_pActionTrackingServices: int | None = None
        self.m_pBulletServices: int | None = None
        self.m_pBuyServices: int | None = None
        self.m_pDamageReactServices: int | None = None
        self.m_pGlowServices: int | None = None
        self.m_pHostageServices: int | None = None
        self.m_qDeathEyeAngles: int | None = None
        self.m_szLastPlaceName: int | None = None
        self.m_szRagdollDamageWeaponName: int | None = None
        self.m_thirdPersonHeading: int | None = None
        self.m_unCurrentEquipmentValue: int | None = None
        self.m_unFreezetimeEndEquipmentValue: int | None = None
        self.m_unPreviousWeaponHash: int | None = None
        self.m_unRoundStartEquipmentValue: int | None = None
        self.m_unWeaponHash: int | None = None
        self.m_vHeadConstraintOffset: int | None = None
        self.m_vRagdollDamageForce: int | None = None
        self.m_vRagdollDamagePosition: int | None = None
        self.m_vRagdollServerOrigin: int | None = None
        self.m_vecBulletHitModels: int | None = None
        self.m_vecDeathInfoOrigin: int | None = None
        self.m_vecPlayerPatchEconIndices: int | None = None
        self.m_vecStashedGrenadeThrowPosition: int | None = None
        self.m_vecStashedVelocity: int | None = None
        self.m_vecThrowPositionHistory: int | None = None
        self.m_vecVelocityHistory: int | None = None
        self.m_angEyeAngles: int | None = None
        self.m_bCachedPlaneIsValid: int | None = None
        self.m_bClipHitStaticWorld: int | None = None
        self.m_bDeferStartMusicOnWarmup: int | None = None
        self.m_bFlashBuildUp: int | None = None
        self.m_bFlashDspHasBeenCleared: int | None = None
        self.m_bFlashScreenshotHasBeenGrabbed: int | None = None
        self.m_bGuardianShouldSprayCustomXMark: int | None = None
        self.m_bGunGameImmunity: int | None = None
        self.m_bHasMovedSinceSpawn: int | None = None
        self.m_bIsRescuing: int | None = None
        self.m_bScreenTearFrameCaptured: int | None = None
        self.m_bShouldAutobuyDMWeapons: int | None = None
        self.m_bShouldAutobuyNow: int | None = None
        self.m_cycleLatch: int | None = None
        self.m_delayTargetIDTimer: int | None = None
        self.m_fImmuneToGunGameDamageTime: int | None = None
        self.m_fImmuneToGunGameDamageTimeLast: int | None = None
        self.m_fMolotovDamageTime: int | None = None
        self.m_fMolotovUseTime: int | None = None
        self.m_fNextThinkPushAway: int | None = None
        self.m_fRenderingClipPlane: int | None = None
        self.m_flClientDeathTime: int | None = None
        self.m_flCurrentMusicStartTime: int | None = None
        self.m_flDeathCCWeight: int | None = None
        self.m_flFlashBangTime: int | None = None
        self.m_flFlashDuration: int | None = None
        self.m_flFlashMaxAlpha: int | None = None
        self.m_flFlashOverlayAlpha: int | None = None
        self.m_flFlashScreenshotAlpha: int | None = None
        self.m_flHealthFadeAlpha: int | None = None
        self.m_flHealthFadeValue: int | None = None
        self.m_flLastSmokeAge: int | None = None
        self.m_flLastSmokeOverlayAlpha: int | None = None
        self.m_flLastSpawnTimeIndex: int | None = None
        self.m_flMusicRoundStartTime: int | None = None
        self.m_flNextMagDropTime: int | None = None
        self.m_flPrevMatchEndTime: int | None = None
        self.m_flPrevRoundEndTime: int | None = None
        self.m_flProgressBarStartTime: int | None = None
        self.m_hOriginalController: int | None = None
        self.m_holdTargetIDTimer: int | None = None
        self.m_iHealthBarRenderMaskIndex: int | None = None
        self.m_iIDEntIndex: int | None = None
        self.m_iOldIDEntIndex: int | None = None
        self.m_iPlayerState: int | None = None
        self.m_iProgressBarDuration: int | None = None
        self.m_iTargetItemEntIdx: int | None = None
        self.m_iThrowGrenadeCounter: int | None = None
        self.m_nLastClipPlaneSetupFrame: int | None = None
        self.m_nLastMagDropAttachmentIndex: int | None = None
        self.m_nPlayerInfernoBodyFx: int | None = None
        self.m_nPlayerInfernoFootFx: int | None = None
        self.m_nPlayerSmokedFx: int | None = None
        self.m_pClippingWeapon: int | None = None
        self.m_pPingServices: int | None = None
        self.m_pViewModelServices: int | None = None
        self.m_previousPlayerState: int | None = None
        self.m_serverIntendedCycle: int | None = None
        self.m_vLastSmokeOverlayColor: int | None = None
        self.m_vecIntroStartEyePosition: int | None = None
        self.m_vecIntroStartPlayerForward: int | None = None
        self.m_vecLastAliveLocalVelocity: int | None = None
        self.m_vecLastClipCameraForward: int | None = None
        self.m_vecLastClipCameraPos: int | None = None
        self.m_AttributeManager: int | None = None
        self.m_OriginalOwnerXuidHigh: int | None = None
        self.m_OriginalOwnerXuidLow: int | None = None
        self.m_bAttachmentDirty: int | None = None
        self.m_bAttributesInitialized: int | None = None
        self.m_bClientside: int | None = None
        self.m_bParticleSystemsCreated: int | None = None
        self.m_flFallbackWear: int | None = None
        self.m_flFlexDelayTime: int | None = None
        self.m_flFlexDelayedWeight: int | None = None
        self.m_hOldProvidee: int | None = None
        self.m_hViewmodelAttachment: int | None = None
        self.m_iNumOwnerValidationRetries: int | None = None
        self.m_iOldTeam: int | None = None
        self.m_nFallbackPaintKit: int | None = None
        self.m_nFallbackSeed: int | None = None
        self.m_nFallbackStatTrak: int | None = None
        self.m_nUnloadedModelIndex: int | None = None
        self.m_vecAttachedModels: int | None = None
        self.m_vecAttachedParticles: int | None = None
        self.m_AttributeList: int | None = None
        self.m_NetworkedDynamicAttributes: int | None = None
        self.m_bDisallowSOC: int | None = None
        self.m_bInitialized: int | None = None
        self.m_bInitializedTags: int | None = None
        self.m_bInventoryImageRgbaRequested: int | None = None
        self.m_bInventoryImageTriedCache: int | None = None
        self.m_bIsStoreItem: int | None = None
        self.m_bIsTradeItem: int | None = None
        self.m_bRestoreCustomMaterialAfterPrecache: int | None = None
        self.m_iAccountID: int | None = None
        self.m_iEntityLevel: int | None = None
        self.m_iEntityQuality: int | None = None
        self.m_iEntityQuantity: int | None = None
        self.m_iInventoryPosition: int | None = None
        self.m_iItemDefinitionIndex: int | None = None
        self.m_iItemID: int | None = None
        self.m_iItemIDHigh: int | None = None
        self.m_iItemIDLow: int | None = None
        self.m_iOriginOverride: int | None = None
        self.m_iQualityOverride: int | None = None
        self.m_iRarityOverride: int | None = None
        self.m_nInventoryImageRgbaHeight: int | None = None
        self.m_nInventoryImageRgbaWidth: int | None = None
        self.m_szCurrentLoadCachedFileName: int | None = None
        self.m_szCustomName: int | None = None
        self.m_szCustomNameOverride: int | None = None
        self.m_unClientFlags: int | None = None
        self.m_unOverrideStyle: int | None = None
        self.m_VoxelFrameData: int | None = None
        self.m_bDidSmokeEffect: int | None = None
        self.m_bSmokeEffectSpawned: int | None = None
        self.m_bSmokeVolumeDataReceived: int | None = None
        self.m_nRandomSeed: int | None = None
        self.m_nSmokeEffectTickBegin: int | None = None
        self.m_nVoxelFrameDataSize: int | None = None
        self.m_nVoxelUpdate: int | None = None
        self.m_vSmokeColor: int | None = None
        self.m_vSmokeDetonationPos: int | None = None
        self.m_bSpotted: int | None = None
        self.m_bSpottedByMask: int | None = None
        self.m_bForcedObserverMode: int | None = None
        self.m_flObserverChaseDistance: int | None = None
        self.m_flObserverChaseDistanceCalcTime: int | None = None
        self.m_hObserverTarget: int | None = None
        self.m_iObserverLastMode: int | None = None
        self.m_iObserverMode: int | None = None

        self.load_offsets(update)

    def load_offsets(self, update=False) -> None:
        local_last_update_date = None
        if constants.LAST_UPDATE_DATE_PATH.exists():
            try:
                local_last_update_date = datetime.datetime.fromisoformat(constants.LAST_UPDATE_DATE_PATH.read_text())
            except ValueError:
                pass

        with requests.Session() as session:
            response = session.get(constants.ENDPOINTS['cs2_dumper_github_commits'])
            if response.ok:
                commit_data = response.json()
                last_update_iso_date = commit_data[0]['commit']['committer']['date']
                constants.LAST_UPDATE_DATE_PATH.write_text(last_update_iso_date)
                last_commit_date = datetime.datetime.fromisoformat(last_update_iso_date)
            else:
                last_commit_date = None

            if (
                update
                or
                not local_last_update_date
                or
                last_commit_date and local_last_update_date < last_commit_date
                or
                not constants.CLIENT_OFFSETS_PATH.exists()
                or
                not constants.GENERAL_OFFSETS_PATH.exists()
            ):
                client_offsets = session.get(constants.ENDPOINTS['client_offsets']).json()
                general_offsets = session.get(constants.ENDPOINTS['general_offsets']).json()

                constants.CLIENT_OFFSETS_PATH.write_text(json.dumps(client_offsets))
                constants.GENERAL_OFFSETS_PATH.write_text(json.dumps(general_offsets))
            else:
                client_offsets = json.loads(constants.CLIENT_OFFSETS_PATH.read_text())
                general_offsets = json.loads(constants.GENERAL_OFFSETS_PATH.read_text())

        for group_name, group_data in general_offsets.items():
            for offset_name, offset in group_data.items():
                setattr(self, offset_name, offset)

        for class_name, class_data in client_offsets[constants.CS_CLIENT_DLL_NAME]['classes'].items():
            if class_name not in constants.REQUIRED_OFFSET_CLASSES:
                continue

            for offset_name, offset in class_data['fields'].items():
                if (
                    (offset_name != 'm_vSmokeColor' or class_name == 'C_SmokeGrenadeProjectile')
                    and
                    (offset_name != 'm_name' or class_name == 'CEntityIdentity')
                ):
                    setattr(self, offset_name, offset)

    def print_offsets_attributes(self) -> None:
        for offset_name in vars(self):
            print(f'self.{offset_name}: int | None = None')


if __name__ == '__main__':
    offsets = Offsets(update=True)
    offsets.print_offsets_attributes()
